
/**
 * psIMU calibration header. Automatically generated by psIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

accel_bias[0] = -15;
accel_bias[1] = -116;
accel_bias[2] = 101;
accel_scale[0] = 3989.403745;
accel_scale[1] = 4245.394956;
accel_scale[2] = 4070.601237;

mag_bias[0] = -19;
mag_bias[1] = -135;
mag_bias[2] = 525;
mag_scale[0] = 402.173311;
mag_scale[1] = 412.483569;
mag_scale[2] = 399.651540;
